import 'package:flutter/material.dart';
import 'linea_model.dart';

final List<Linea> lineasMock = [
  Linea(
    id: '1',
    numero: '1',
    nombre: 'Centro - Playa',
    rutaDescripcion: 'Centro comercial - Playas del Este',
    color: const Color(0xFF667eea),
    horarioInicio: '06:00',
    horarioFin: '23:00',
    paradas: ['Centro', 'Paseo Marítimo', 'Playa Grande', 'Playa Chica'],
  ),
  Linea(
    id: '2',
    numero: '2',
    nombre: 'Estación - Barrio Nuevo',
    rutaDescripcion: 'Estación central - Residencial Norte',
    color: const Color(0xFF764ba2),
    horarioInicio: '05:30',
    horarioFin: '23:30',
    paradas: ['Estación', 'Hospital', 'Universidad', 'Barrio Nuevo'],
  ),
  Linea(
    id: '3',
    numero: '3',
    nombre: 'Aeropuerto - Centro',
    rutaDescripcion: 'Aeropuerto - Centro comercial',
    color: const Color(0xFFf093fb),
    horarioInicio: '04:00',
    horarioFin: '23:59',
    paradas: ['Aeropuerto', 'Zona Industrial', 'Centro', 'Terminal'],
  ),
  Linea(
    id: '4',
    numero: '4',
    nombre: 'Parque - Mercado',
    rutaDescripcion: 'Parque Central - Mercado Municipal',
    color: const Color(0xFF4facfe),
    horarioInicio: '06:30',
    horarioFin: '22:00',
    paradas: ['Parque', 'Biblioteca', 'Mercado', 'Zona Peatonal'],
  ),
  Linea(
    id: '5',
    numero: '5',
    nombre: 'Hospital - Estadio',
    rutaDescripcion: 'Hospital - Estadio Municipal',
    color: const Color(0xFF43e97b),
    horarioInicio: '07:00',
    horarioFin: '21:00',
    paradas: ['Hospital', 'Clínica', 'Parque Deportivo', 'Estadio'],
  ),
];

final List<Bus> busesActivosMock = [
  Bus(
    id: 'bus-1',
    lineaId: '1',
    numeroLinea: '1',
    ubicacion: 'Paseo Marítimo',
    tiempoEstimado: 3,
    latitud: 39.4699,
    longitud: -0.3763,
    pasajeros: 24,
    estado: 'En marcha',
  ),
  Bus(
    id: 'bus-2',
    lineaId: '2',
    numeroLinea: '2',
    ubicacion: 'Av. Principal',
    tiempoEstimado: 7,
    latitud: 39.4700,
    longitud: -0.3764,
    pasajeros: 18,
    estado: 'En marcha',
  ),
  Bus(
    id: 'bus-3',
    lineaId: '3',
    numeroLinea: '3',
    ubicacion: 'Zona Industrial',
    tiempoEstimado: 2,
    latitud: 39.4698,
    longitud: -0.3762,
    pasajeros: 31,
    estado: 'En marcha',
  ),
  Bus(
    id: 'bus-4',
    lineaId: '1',
    numeroLinea: '1',
    ubicacion: 'Centro',
    tiempoEstimado: 12,
    latitud: 39.4701,
    longitud: -0.3765,
    pasajeros: 15,
    estado: 'En marcha',
  ),
  Bus(
    id: 'bus-5',
    lineaId: '4',
    numeroLinea: '4',
    ubicacion: 'Parque Central',
    tiempoEstimado: 5,
    latitud: 39.4699,
    longitud: -0.3761,
    pasajeros: 22,
    estado: 'En marcha',
  ),
  Bus(
    id: 'bus-6',
    lineaId: '5',
    numeroLinea: '5',
    ubicacion: 'Hospital',
    tiempoEstimado: 1,
    latitud: 39.4702,
    longitud: -0.3766,
    pasajeros: 8,
    estado: 'En estación',
  ),
];

final List<Parada> paradasMock = [
  Parada(
    id: 'parada-1',
    nombre: 'Centro',
    latitud: 39.4699,
    longitud: -0.3763,
    lineasQueParam: ['1', '2', '3'],
  ),
  Parada(
    id: 'parada-2',
    nombre: 'Estación',
    latitud: 39.4700,
    longitud: -0.3764,
    lineasQueParam: ['2', '3'],
  ),
  Parada(
    id: 'parada-3',
    nombre: 'Playa',
    latitud: 39.4698,
    longitud: -0.3762,
    lineasQueParam: ['1'],
  ),
];
